# .github/workflows/update.yml
name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # runs an hour past midnight

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: nix flake update --commit-lock-file
    - name: Push changes
      run: git push
